sonar.organization=kalyo-silva
sonar.projectKey=6ff73e034be3af77f0bb703cc1ae326877732968

sonar.sources=backend,public
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**
sonar.exclusions=node_modules/**